export const getFlagEmoji = (countryCode: string) => {
    const codePoints = countryCode
        .toUpperCase()
        .split('')
        .map((char) => 127397 + char.charCodeAt(0));
    return String.fromCodePoint(...codePoints);
};

export const COUNTRY_CODES = [
    { code: '+1', country: 'US', name: 'United States' },
    { code: '+1', country: 'CA', name: 'Canada' },
    { code: '+7', country: 'RU', name: 'Russia' },
    { code: '+20', country: 'EG', name: 'Egypt' },
    { code: '+27', country: 'ZA', name: 'South Africa' },
    { code: '+30', country: 'GR', name: 'Greece' },
    { code: '+31', country: 'NL', name: 'Netherlands' },
    { code: '+32', country: 'BE', name: 'Belgium' },
    { code: '+33', country: 'FR', name: 'France' },
    { code: '+34', country: 'ES', name: 'Spain' },
    { code: '+36', country: 'HU', name: 'Hungary' },
    { code: '+39', country: 'IT', name: 'Italy' },
    { code: '+40', country: 'RO', name: 'Romania' },
    { code: '+41', country: 'CH', name: 'Switzerland' },
    { code: '+43', country: 'AT', name: 'Austria' },
    { code: '+44', country: 'GB', name: 'United Kingdom' },
    { code: '+45', country: 'DK', name: 'Denmark' },
    { code: '+46', country: 'SE', name: 'Sweden' },
    { code: '+47', country: 'NO', name: 'Norway' },
    { code: '+48', country: 'PL', name: 'Poland' },
    { code: '+49', country: 'DE', name: 'Germany' },
    { code: '+51', country: 'PE', name: 'Peru' },
    { code: '+52', country: 'MX', name: 'Mexico' },
    { code: '+53', country: 'CU', name: 'Cuba' },
    { code: '+54', country: 'AR', name: 'Argentina' },
    { code: '+55', country: 'BR', name: 'Brazil' },
    { code: '+56', country: 'CL', name: 'Chile' },
    { code: '+57', country: 'CO', name: 'Colombia' },
    { code: '+58', country: 'VE', name: 'Venezuela' },
    { code: '+60', country: 'MY', name: 'Malaysia' },
    { code: '+61', country: 'AU', name: 'Australia' },
    { code: '+62', country: 'ID', name: 'Indonesia' },
    { code: '+63', country: 'PH', name: 'Philippines' },
    { code: '+64', country: 'NZ', name: 'New Zealand' },
    { code: '+65', country: 'SG', name: 'Singapore' },
    { code: '+66', country: 'TH', name: 'Thailand' },
    { code: '+81', country: 'JP', name: 'Japan' },
    { code: '+82', country: 'KR', name: 'South Korea' },
    { code: '+84', country: 'VN', name: 'Vietnam' },
    { code: '+86', country: 'CN', name: 'China' },
    { code: '+90', country: 'TR', name: 'Turkey' },
    { code: '+91', country: 'IN', name: 'India' },
    { code: '+92', country: 'PK', name: 'Pakistan' },
    { code: '+93', country: 'AF', name: 'Afghanistan' },
    { code: '+94', country: 'LK', name: 'Sri Lanka' },
    { code: '+95', country: 'MM', name: 'Myanmar' },
    { code: '+98', country: 'IR', name: 'Iran' },
    { code: '+212', country: 'MA', name: 'Morocco' },
    { code: '+213', country: 'DZ', name: 'Algeria' },
    { code: '+216', country: 'TN', name: 'Tunisia' },
    { code: '+218', country: 'LY', name: 'Libya' },
    { code: '+220', country: 'GM', name: 'Gambia' },
    { code: '+221', country: 'SN', name: 'Senegal' },
    { code: '+234', country: 'NG', name: 'Nigeria' },
    { code: '+254', country: 'KE', name: 'Kenya' },
    { code: '+351', country: 'PT', name: 'Portugal' },
    { code: '+352', country: 'LU', name: 'Luxembourg' },
    { code: '+353', country: 'IE', name: 'Ireland' },
    { code: '+354', country: 'IS', name: 'Iceland' },
    { code: '+355', country: 'AL', name: 'Albania' },
    { code: '+358', country: 'FI', name: 'Finland' },
    { code: '+359', country: 'BG', name: 'Bulgaria' },
    { code: '+370', country: 'LT', name: 'Lithuania' },
    { code: '+371', country: 'LV', name: 'Latvia' },
    { code: '+372', country: 'EE', name: 'Estonia' },
    { code: '+375', country: 'BY', name: 'Belarus' },
    { code: '+380', country: 'UA', name: 'Ukraine' },
    { code: '+381', country: 'RS', name: 'Serbia' },
    { code: '+385', country: 'HR', name: 'Croatia' },
    { code: '+386', country: 'SI', name: 'Slovenia' },
    { code: '+420', country: 'CZ', name: 'Czech Republic' },
    { code: '+421', country: 'SK', name: 'Slovakia' },
    { code: '+966', country: 'SA', name: 'Saudi Arabia' },
    { code: '+971', country: 'AE', name: 'United Arab Emirates' },
    { code: '+972', country: 'IL', name: 'Israel' },
];
